# Generated by Django 4.2.2 on 2023-06-14 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('ects', models.IntegerField()),
                ('ano_letivo', models.CharField(max_length=100)),
                ('topicos_abordados', models.TextField()),
                ('ranking', models.IntegerField()),
                ('pagina_cadeira', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('imagem', models.ImageField(upload_to='noticias/')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('linkedin', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TrabalhoFinalCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('ano_realizacao', models.IntegerField()),
                ('sumario', models.TextField()),
                ('resumo', models.CharField(max_length=500)),
                ('relatorio', models.URLField(blank=True)),
                ('repositorio_github', models.URLField(blank=True)),
                ('video_youtube', models.URLField(blank=True)),
                ('autor', models.ManyToManyField(to='portfolio.pessoa')),
                ('orientador', models.ManyToManyField(related_name='orientador', to='portfolio.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=500)),
                ('imagem', models.ImageField(upload_to='projetos/')),
                ('ano_realizacao', models.IntegerField()),
                ('repositorio_github', models.URLField(blank=True)),
                ('video_youtube', models.URLField(blank=True)),
                ('tecnologias_usadas', models.CharField(max_length=200)),
                ('competencias', models.CharField(max_length=100)),
                ('cadeira', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.disciplina')),
                ('participantes', models.ManyToManyField(to='portfolio.pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='disciplina',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.pessoa'),
        ),
    ]
