# Generated by Django 4.2.2 on 2023-06-15 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_noticia_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
